### PR TITLE
Default executeCommand arguments to an empty array

### PR DESCRIPTION
**Pull request by BasThomas**
I'll add a test, let's wait with merging

### CODE REVIEW

**Comment by q231950** [comment]
Nice @BasThomas 👍

**Comment by BasThomas** [comment]
Ping @q231950 :)

**Comment by q231950** [comment]
@BasThomas I will make the necessary changes to make the `CommandExecutor` better testable.

**Comment by q231950** [comment]
@BasThomas this will help I hope 🤞https://github.com/q231950/commands/pull/8

**Comment by BasThomas** [comment]
I'll fix the tests later 👍

**Comment by q231950** [comment]
@BasThomas I think we can close this pr, what do you think?

**Pull request closed without merging**
